Clientes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from Clientes.views import Bienvenida,Inicio, Mensaje, Promo,SignUpView,SignOutView,SignInView
from carts.views import  view, updatecart
from Productos.views import Wensaladas, Chelados, malteadas


urlpatterns=[
    path('Home/',Inicio,name="inicio"),
    path('Mensaje/',Mensaje,name="mensaje"),
    path('Registro/',SignUpView, name='sign_up'),
    path('Login/',SignInView.as_view(), name='sign_in'),
    path('Logout/',SignOutView.as_view(), name='sign_out'),
    path('Promociones/',Promo, name="promo"),
    path('Malteadas/',malteadas,name="malteadas"),
     path('Bienvenido/',Bienvenida,name="bienvenida"),
    path('cart/',view, name="cart"),
    path('cart/<slug:slug>/',updatecart , name="updatecart"),
    path('Waffles/',Wensaladas, name="single_ho"),
    path('CopasHelado/',Chelados, name="Chelados"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Estructuras/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from Clientes.views import Bienvenida,Inicio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Inicio),
    path('',include(('Clientes.urls','Clientes'), namespace='Clientes')),
] 

carts/models.py
from django.db import models

from Productos.models import Producto,CopasHelados,Malteada

class Cart(models.Model): # este es el de waffles
    #items = models.ManyToManyField(CartItem)
    #Productos=models.ManyToManyField(Producto)
    #Producto2=models.ManyToManyField(CopasHelados)
    #Producto3=models.ManyToManyField(Malteada)
    total=models.IntegerField(default=0)
    active=models.BooleanField(default=True)

    def __str__(self):
        return "Cart id: %s"  % (self.id) # lo que nos va aparecer

class CartItem(models.Model): # esto es para que me deje agregar mas de un solo producto al carrito de compra
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE,null=True,blank=True)
    Producto1= models.ForeignKey(Producto, on_delete=models.CASCADE,)
    quantity= models.IntegerField(default=1) # comienza en 1 pero se ira agregando mas 
    line_total= models.IntegerField(default=10)

    def __str__(self):
        try:
            return str(self.cart.id)
        except:
            return self.Producto1.titel   

class CartItem2(models.Model): # esto es para que me deje agregar mas de un solo producto al carrito de compra
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE,null=True,blank=True)
    Producto2= models.ForeignKey(CopasHelados, on_delete=models.CASCADE,)
    quantity= models.IntegerField(default=1) # comienza en 1 pero se ira agregando mas 
    line_total= models.IntegerField(default=10)

    def __str__(self):
        try:
            return str(self.cart.id)
        except:
            return self.Producto2.titel  

class CartItem3(models.Model): # esto es para que me deje agregar mas de un solo producto al carrito de compra
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE,null=True,blank=True)
    Producto3= models.ForeignKey(Malteada, on_delete=models.CASCADE,)
    quantity= models.IntegerField(default=1) # comienza en 1 pero se ira agregando mas 
    line_total= models.IntegerField(default=10)

    def __str__(self):
        try:
            return str(self.cart.id)
        except:
            return self.Producto3.titel  
    
   

templates/Helados.html
{% extends "header.html" %}
{% load static  %}
{% block content %}

<link href="https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/bootstrap.min.css" rel="stylesheet">
<link href=".https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/main.css">
<link rel="stylesheet" type="text/css" href="{% static 'Helados.css' %}" media="screen" />  
    <br>  
   <div > 
    <li id="item">
        <button><img src="{% static 'Imagenes/menu.jpg' %}" width="50" height="50"></button>
        <ul id="desple">
            <li class="menuhelados"><a href="{% url 'Clientes:Chelados' %}">Copas de helado</a></li>
            <li class="menuhelados"><a href="{% url 'Clientes:single_ho' %}">Waffles y ensalada de frutas</a></li>
            <li class="menuhelados"><a href="{% url 'Clientes:malteadas' %}">Malteadas</a></li>
        </ul>
   </li>
  </div>
    <div class='row' style="position:relative; margin: 40px 0 0 120px;">

    {% for producto in Productos %} 
        <div class='col-sm-4'>
            <img class='img-responsive' src="{{MEDIA_URL}}{{ producto.image }}"/>
            <h3>{{ producto.nombre}}</h3><br>
            <p>Precio: {{producto.precio}} </p>
            <p>{{producto.descripcion}} </p>
            <form  method='GET' action='/cart/{{ producto.slug}}'>
                <input name='qty' type='number' min="0" value='1' />
                <input type='submit' class="btn btn-primary"  value='Agregar a carrito'/>
            </form>
            <br>
        </div>

    {%endfor%} 
    </div>
    <br>
{%endblock%}

templates/carrito.html
{% extends "header.html" %}
{% load static  %}
{% block content %}
<link href="https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/bootstrap.min.css" rel="stylesheet">
<link href=".https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/main.css">
<link rel="stylesheet" type="text/css" href="{% static 'Helados.css' %}" media="screen" /> 
{%if empty or cart.total == 0 %}

    <h1 style='text-align:center'> Aún no tienes nada en el carrito, </h1>
    <h1 style='text-align:center'>vuelve a domicilio para realizar tu pedido</h1>
    <center><img src="{% static 'Imagenes/domicilios.jpg' %}"></center>
    <br>
{% else %}
<link rel="stylesheet" type="text/css" href="{% static 'carro.css' %}" media="screen" />  

<br>
<center>
<table>
<thead>
<th style="text-align: center">Nombre</th>
<th style="text-align: center">Precio</th>
<th>Cantidad</th>
<th></th>
</thead>
<tfoot>
<tr>
<td></td>
<td>Total: {{cart.total}}</td>
<td></td>
</tr>
</tfoot>

{% for item in cart.cartitem_set.all %}
        <tr><td> {{ item.Producto1 }}</td><td class="precio">{{ item.Producto1.precio }}</td><td style="text-align: center">{{ item.quantity }} </td><td><a href='{{ item.Producto1.slug}}/?qty=0'>Eliminar</a></td></tr>
{% endfor %}


{% for item in cart.cartitem2_set.all %}
        <tr><td> {{ item.Producto2 }}</td><td class="precio">{{ item.Producto2.precio }}</td><td style="text-align: center">{{ item.quantity }} </td><td><a href='{{ item.Producto2.slug}}/?qty=0'>Eliminar</a></td></tr>
{% endfor %}

{% for item in cart.cartitem3_set.all %}
        <tr><td> {{ item.Producto3 }}</td><td class="precio">{{ item.Producto3.precio }}</td><td style="text-align: center">{{ item.quantity }} </td><td><a href='{{ item.Producto3.slug}}/?qty=0'>Eliminar</a></td></tr>
{% endfor %}

</table>
</center>
<br><br>
{% endif %}
{% endblock %}

templates/carrusel.html
{% load static  %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/navbar/">

    <title>Dulce capricho</title>

   <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="https://getbootstrap.com/docs/3.4/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
   
   <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/3.4/examples/navbar/navbar.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="https://getbootstrap.com/docs/3.4/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
 <body>
 <div class="container">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="{% static 'Imagenes/carru.png' %}" alt="...">
              <div class="carousel-caption">
                ...
              </div>
            </div>
            <div class="item">
              <img src="{% static 'Imagenes/carru2.png' %}" alt="...">
              <div class="carousel-caption">
              </div>
            </div>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    
    <script src="https://getbootstrap.com/docs/3.4/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/confirmaEnvio.html
{% extends "header.html" %}
{% load static  %}
{% block content %}

<link href="https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/bootstrap.min.css" rel="stylesheet">
<link href=".https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/main.css">

<center>
<h2>Su mensaje fue enviado exitosamente<h2>
<h2> Gracias por escribirnos</h2>
<img src="{% static 'Imagenes/mail.gif' %}">
</center>

<br>
{%endblock%}

templates/footer.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <footer class="footer">
        <div>
            <a href="https://www.google.com/maps/place/Dulce+capricho+helados+y+malteadas/@6.2637262,-75.5718313,17z/data=!3m1!4b1!4m5!3m4!1s0x8e4429bc497cca8f:0x3c3f92f32a74d7e0!8m2!3d6.2637262!4d-75.5696426?hl=es" ><img src="{% static 'Imagenes/ubicacion.gif' %}"width="50" height="50"></a>
            <p> Gracias por visitarnos. </p>
            <p>Dirección: calle 56# 65-39 </p>
            <p> Télefono: 3054347713 </p>
        </div>
    </footer>
</body>
</html>

templates/formulario.html
{% extends "header.html" %}
{% load static  %}
{% block content %}
<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="{% static 'eFormulario.css' %}">
    <div class="form">
    <form action=""id="form" method="POST" >{% csrf_token %}
        <!--
            Formulario SignUpForm creado en forms.py de Clientes.

        -->
        <h1>Registro</h1>
        {% for campos in form %}
        <div class="grupo">
            {{campos}}
            {{campos.label_tag}}
            {{campos.errors}}
        </div>
        {% endfor %}
        <!--
            Formulario PerfilUserForm creado en forms.py de Clientes.
            
        -->
        {% for campos in perfil_form %}
        <div class="grupo">
            {{campos}}
            {{campos.label_tag}}
            {{campos.errors}}
        </div>
        {% endfor %}
        <input type="submit" value="Registrate"> 
    </form>
    <br>
    <center>
        <a class="boton_personalizado" href="{% url 'Clientes:sign_in' %}">Iniciar Sesión</a>
    </center>
    </div>
<script>
    $(function () {
        $('.datetime-input').datetimepicker({
            format:'YYYY-MM-DD '
        });
    });
</script>
{% endblock %}

templates/header.html
{% comment %} Esta es la clase base de esta heredan las demas {% endcomment %}

{% load static  %}  
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'eHeader.css' %}" media="screen" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dulce Capricho</title>
</head>
<body>
    <header class="header">
        <div class="flex-container">
            <div><img src="{% static 'Imagenes/logo.gif' %}" width="150" height="150"></div>
            <nav class="navigation" >
                <ul>                   
                    <li><a href="{% url 'Clientes:inicio' %}">HOME</a></li> 
                    <li><a href="{% url 'Clientes:promo' %}">PROMOCIONES</a></li>
                    <li><a href="{% url 'Clientes:Chelados' %}">DOMICILIOS</a></li>
                    <!---
                        Otra manera de llamar los url de las aplicaciones, sólo se coloca el nombre
                        de la aplicacion, : y el nombre de la dirección.
                    -->
                    <li><a href="{% url 'Clientes:sign_up' %}">REGÍSTRATE</a></li>
                    <li><a href="{% url 'Clientes:mensaje' %}">CONTÁCTANOS</a></li>
                    <li><a href="{% url 'Clientes:cart' %}"><img src="{% static 'Imagenes/carrito.gif' %}"width="40" height="40"> <span class="badge">{{ request.session.items_total}}</a></li> <!--numero de elementos en el carrito-->
                    <li><a href="https://www.facebook.com/Dulcecaprichoheladosymalteadas" ><img src="{% static 'Imagenes/face.png' %}"width="40" height="40"></a></li>
                </ul>          
            </nav>
        </div>
    </header>
    <!---
        Imagen que aparece al lado derecho. Se despliega el nombre y la opción de salir.
    -->
    <div id="perfil" class="perfil" style="float: right;" >
        <img src="{% static 'Imagenes/perfil.png' %}" style=" width:100px; height:50px;">
        <ul id="contenido">
            <li >{{user.username}}</li>
            <li ><a style="font-size: 16px" class="salir" href="{% url 'Clientes:sign_out' %}">Salir</a></li>
        </ul>
    </div>
   

 {% block content %}
{% comment %} acá va el contenido que va a cambiar en las otras plantillas {% endcomment %}
<!--
    Galería de imágenes que se muestra cuando el usuario haga login o se cree un usuario 
    llenando el formulario.
-->   
<div class="contenido">
        
        <div class="galeria">
            <h1>Bienvenido {{user.first_name | title}}  {{user.last_name | title}} a Dulce Capricho</h1>
            <div class="linea"></div> 
            <div class="contenedor-imagenes">
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado1.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado2.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado3.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado4.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado5.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado6.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado7.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado8.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
                <div class="imagen">
                    <img src="{% static 'Imagenes/helado9.jpg' %}">
                    <div class="overlay">
                        <h2>Dulce Capricho</h2>
                    </div>
                </div>
            </div>
            <h1>Disfruta de nuestros productos. El helado te hace feliz</h1>
        </div>
       
    </div>
{% endblock %}

 {% include "footer.html"%}
</body>

</html>

templates/home.html
{% extends "header.html" %}
{% load static  %}

{% block content %}
     <link rel="stylesheet" type="text/css" href="{% static 'eHome.css' %}" media="screen" />
     <main>
        <br></br>
        <div> {% include "carrusel.html"%} <div>
        <div class="container">
            <h3 class="centrar"> Siempre es un buen momento para disfrutar de un delicioso helado</h3>
            <h3> Misión</h3>
            <p class="parrafo"> Dulce capricho pretende ser un lugar para compartir de un momento agradable con amigos,
                familiares o grupo de trabajo; brindándoles carta con más de 50 productos donde encontrán 
                variedad de copas de helado, waffles, malteadas, copas infantiles y cafés; todos nuestros 
                productos son realizados con material de calidad y con mucho amor, para que todos puedan 
                visitarnos en una fecha especial, como la celebración de cumpleaños,día de la madre, día 
                de la mujer, día del amory la amistad o puede ser el mejor lugar para darse un premio y calmar
                un antojo.
            </p>
            <p class="parrafo">Igualamente brindamos atención a eventos y servicio de refrigerios</p>
            <h3> Visión</h3>
            <p class="parrafo">En el 2021 estaremos ubicados en varios Municipios de Antioquia, donde seremos elsitio ideal  y escogido
               por los clientes para disfrutar de ricas copas de helado, waffles,malteadas, ensaladas de fruta, salpicones y cafés;
               con la mejor atención al público, donde se sentirá cómodo y consentido al ingresar a nuestro negocio en compañía de amigos
               y familiares    
            </p>
        </div>
    </main>

 {% endblock %}

templates/login.html
{% extends "header.html" %}
{% load static  %}

{% block content %}
<link rel="stylesheet" href="{% static 'eLogin.css' %}">
<div  class="form">
    <img  class="logo" src="{% static 'Imagenes/logo.gif' %}">
    <h1>Login Here</h1>
    <form method="POST" id="form">{% csrf_token %}
        {% for campos in form %}
        <div class="grupo">
            {{campos}}
            {{campos.label_tag}}
            {{campos.errors}}
        </div>
        {% endfor %} 
        <input type="submit" value="Login">
    </form>
   
    <center>
     <a href="">Crea una Cuenta</a>
     <br>
     <a href="">¿Olvídaste tu contraseña?</a>
    </center>
</div> 
{% endblock %}

templates/mensaje.html
{% extends "header.html" %}
{% load static  %}

{% block content %}
<link href="https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/bootstrap.min.css" rel="stylesheet">
<link href=".https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/main.css">
<link rel="stylesheet" type="text/css" href="{% static 'Helados.css' %}" media="screen" /> 
<link rel="stylesheet" href="{% static 'eMensaje.css' %}">
<form action="" method="POST" id="form">
    <div class="form">
        <h1>Contacto</h1>
        <div class="grupo">
            <input type="text" name="asunto" id="name" required><samp class="barra"></samp>
            <label for="">Asunto</label>
        </div>
        <div class="grupo">
            <input type="email" name="email" id="email" required><samp class="barra"></samp>
            <label for="">Email</label>
        </div>
        <div class="grupo">
            <input type="text" name="mensaje" id="Mensaje" style="height: 200px;" required><samp class="barra"></samp>
            <label for="">Mensaje</label>
        </div>
       <button type="submit" >Enviar</button> 
        <p class="warnings" id="warnings"></p>
    </div>
</form>
{% endblock %}

templates/promociones.html
{% extends "header.html" %}
{% load static  %}

{% block content %}

<link href="https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/bootstrap.min.css" rel="stylesheet">
<link href=".https://uniwebsidad.com/static/libros/ejemplos/bootstrap-3/css/main.css">
<link rel="stylesheet" type="text/css" href="{% static 'Helados.css' %}" media="screen" /> 

    <center>
        <img src="{% static 'Imagenes/promo.jpg' %}" width="500" height="500">
    </center>

{% endblock %}